export default {
  LOAD_MORE_GIF: 'LOAD_MORE_GIF',
  RESET: 'RESET',
  LOAD_MORE_GIF_OK: 'LOAD_MORE_GIF_OK',
  HANDLE_SEARCH: 'HANDLE_SEARCH',
  LOAD_MORE_GIF_SEARCH: 'LOAD_MORE_GIF_SEARCH',
  LOAD_MORE_GIF_SEARCH_OK_FIRST_LOAD: 'LOAD_MORE_GIF_SEARCH_OK_FIRST_LOAD',
  LOAD_MORE_GIF_SEARCH_OK: 'LOAD_MORE_GIF_SEARCH_OK',
  DETAIL_GIF: 'DETAIL_GIF',
};
